<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Afterglow.Core\Afterglow.Core.csproj" />
    <ProjectReference Include="..\Afterglow.HubClient\Afterglow.HubClient.csproj" />
    <ProjectReference Include="..\Afterglow.LocalStore\Afterglow.LocalStore.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
